name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.0b3-alpine3.12
      steps:
        - name: Log python version
          run: |
            python --version
            cat /etc/os-release
